### ISSUE TITLE
missing teaching object

### ISSUE THREAD

**Issue by hassan1091** [mutairibassam/Android-Basics#11]
just added projects that require

**Comment by mutairibassam** [comment]
Thanks @hassan1091 for your contribution. Can you please be specific and list all the changes?

**Comment by hassan1091** [comment]
Required projects for student 
project 1, 2 and 3

**Comment by mutairibassam** [comment]
All project's documents which not markdown files, should be shared through cloud. Please use the google drive to share such documents.
